class Park
  attr_reader :unique_name,
              :admission_price,
              :vehicles

  def initialize(unique_name, admission_price)
    @unique_name = unique_name
    @admission_price = admission_price
    @vehicles = []
  end

  def add_vehicle(vehicle)
    @vehicles << vehicle
  end

  def passengers
    @vehicles.flat_map(&:passengers) 
  end
# This code is retrieving all the passengers from the vehicles
# in the @vehicles array and returning them as a single array.

  def revenue
    adult_passengers = passengers.select(&:adult?)
    adult_passengers.count * @admission_price
  end
# calculates the total revenue generated by multiplying the count of 
# adult passengers by the admission price per adult. 
# It relies on the passengers array to determine the number of adult 
# passengers through the use of the select method.
end